'use client';
import {useState} from 'react';
import {Tabs, TabsList, TabsTrigger} from '@/components/ui/tabs';
const directions=[{id:'earth',name:'01 · Rooted',label:'Warm & local',title:<>Good buildings begin<br/>with <em>good bricks.</em></>,intro:'Made in Palakkad. Ready for your next chapter.'},{id:'bold',name:'02 · Groundwork',label:'Bold & industrial',title:<>BUILT FROM ASH.<br/><em>MADE TO LAST.</em></>,intro:'Fly ash bricks. Factory direct. NEO BRICKS.'},{id:'light',name:'03 · Form',label:'Clean & architectural',title:<>A solid beginning.<br/><em>A considered finish.</em></>,intro:'Fly ash bricks, crafted in Palakkad, Kerala.'}];
export default function Home({initialStyle='earth',fixedStyle=false}:{initialStyle?:string,fixedStyle?:boolean}){const [style,setStyle]=useState(initialStyle);const d=directions.find(x=>x.id===style)!;return <main className={style}>
<div className="preview" style={fixedStyle?{display:"none"}:undefined}><span>DESIGN STUDY <b>NEO BRICKS</b></span><Tabs value={style} onValueChange={v=>setStyle(String(v))}><TabsList aria-label="Choose a design direction">{directions.map(x=><TabsTrigger key={x.id} value={x.id}>{x.name}</TabsTrigger>)}</TabsList></Tabs><small>Preview · {d.label}</small></div>
<nav><a className="brand" href="#home"><span className="mark">NB</span><span>NEO BRICKS<small>PALAKKAD, KERALA</small></span></a><div className="navlinks"><a href="#benefits">Why fly ash?</a><a href="#bricks">Our bricks</a><a href="#quality">Quality</a></div><a className="navcall" href="tel:+918075307418">Let’s talk <span>↗</span></a></nav>
<section className="hero" id="home" key={style}><div className="hero-text"><p className="eyebrow"><span/> FROM OUR FACTORY. FOR YOUR FUTURE.</p><h1>Quality bricks.<br/><em>Solid beginnings.</em></h1><p className="intro">{d.intro} From a family home to your next project, start with a material you can see and a team you can speak to.</p><div className="actions"><a className="button" href="#contact">Plan your build <span>↗</span></a><a className="textlink" href="#story">Discover our story <span>↓</span></a></div><div className="heronote">FLY ASH BRICKS <span>—</span> ALL-INDIA TRANSPORTATION</div></div><div className="hero-image"><img src="/assets/brick-stock-01.png" alt="NEO BRICKS fly ash bricks stacked at the factory"/><div className="photo-caption"><span>THE MATERIAL BEHIND YOUR NEXT BUILD</span><b>Quality in every brick.</b></div><span className="seal">MADE IN<br/><strong>PALAKKAD</strong><br/>KERALA</span></div></section>
<div className="ribbon"><span>Made locally.</span><span>Build confidently.</span><span>Delivered across India.</span></div>
<section id="story" className="story section"><div className="story-image"><img src="/assets/factory-yard-01.png" loading="lazy" alt="Fly ash bricks arranged on pallets inside the NEO BRICKS production yard"/><span>01 / THE MATERIAL BEHIND YOUR NEXT BUILD</span></div><div className="story-copy"><p className="eyebrow">ROOTED IN PALAKKAD. BUILT ON QUALITY.</p><h2>Good materials.<br/>A <em>personal commitment.</em></h2><p>Every building starts with a choice. At NEO BRICKS, we manufacture fly ash bricks in Palakkad and help you choose the supply your project needs.</p><p>Speak directly with our team about quantities, availability and delivery. From your first enquiry to planning transportation, we keep the conversation clear and practical.</p><a className="textlink" href="#contact">Talk to our team <span>↗</span></a><div className="address-mini">PALAKKAD, KERALA<br/>ALL-INDIA TRANSPORTATION AVAILABLE</div></div></section>
<section className="products section" id="bricks"><div className="section-heading"><div><p className="eyebrow">A SIMPLE MATERIAL. AN IMPORTANT CHOICE.</p><h2>Meet your building’s<br/><em>first building block.</em></h2></div><p>Fly ash bricks for construction projects that call for consistent form and a clean finish.</p></div><div className="product-grid"><img loading="lazy" src="/assets/brick-detail-01.png" alt="Close view of NEO BRICKS fly ash bricks"/><div className="product-copy"><span className="product-number">01 — OUR PRODUCT</span><h3>Fly ash bricks</h3><p>Clean edges. Consistent form. A solid place to start.</p>{['Discuss the right quantity for your project','Check current stock and availability','Arrange transportation to your location'].map((x,i)=><div className="feature" key={x}><span>0{i+1}</span>{x}</div>)}<a href="https://wa.me/918075307418?text=Hello%20NEO%20BRICKS%2C%20I%20would%20like%20to%20enquire%20about%20fly%20ash%20bricks." target="_blank" rel="noreferrer" className="button">Ask about our bricks ↗</a></div></div></section>
<section id="benefits" className="benefits section"><div className="section-heading"><div><p className="eyebrow">WHY CHOOSE FLY ASH BRICKS?</p><h2>Better choices.<br/><em>Brick by brick.</em></h2></div><p>Practical advantages for your build, with a more resource-conscious approach to materials.</p></div><div className="benefit-grid">{[
['Consistent dimensions','Machine forming helps produce regular shapes and sizes for more orderly masonry.'],
['Potential mortar savings','Uniform units can allow more consistent joints, reducing mortar use compared with uneven clay bricks.'],
['A smoother finish','Even surfaces can reduce levelling and finishing work, depending on the finish your project requires.'],
['Controlled production','Measured mixes and machine forming support repeatable production and quality checks.'],
['A useful second life','Fly ash from thermal power generation becomes a building material instead of a disposal burden.'],
['Conserving topsoil','Replacing clay with fly ash helps reduce demand for fertile soil used in conventional brickmaking.'],
['Less firing energy','Cured, non-fired fly ash bricks avoid the kiln-firing stage of conventional burnt-clay bricks.'],
['An established masonry option','Fly ash bricks are an alternative to common clay bricks when the specified grade suits the application.']
].map(([title,body],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{body}</p></article>)}</div><p className="benefit-note">Benefits vary with the mix, manufacturing, curing and workmanship. Confirm project suitability and product test results with your engineer.</p><details className="sources"><summary>Read the material guidance</summary><p>General material benefits are summarised from <a href="https://rdso.indianrailways.gov.in/works/uploads/File/Fly%20ash%20brick.pdf" target="_blank" rel="noreferrer">Indian Railways RDSO: Fly Ash Brick ↗</a>. This reference is not a certification or endorsement of NEO BRICKS.</p></details></section>
<section id="quality" className="quality section"><span className="quality-symbol">↗</span><div><p className="eyebrow">LOOK BEYOND THE SURFACE</p><h2>Quality you can<br/><em>ask questions about.</em></h2><p>View the laboratory report from N.S.S. College of Engineering, Palakkad, for the tested brick samples. Talk to us about your project’s requirements.</p><a className="textlink" href="/assets/lab-test-report.jpeg" target="_blank" rel="noreferrer">View the laboratory report ↗</a></div></section>
<section className="section faq" id="questions"><p className="eyebrow">BEFORE YOU BUILD</p><h2>A few good <em>questions.</em></h2><details><summary>Are fly ash bricks right for my project?</summary><p>They can be used as an alternative to conventional clay bricks in suitable masonry applications. Ask your engineer to confirm the required brick grade, wall design and mortar for your project.</p></details><details><summary>What should I check before ordering?</summary><p>Confirm dimensions, quantity, current availability, test results and delivery requirements. Share your location and project details with our team for a quotation.</p></details><details><summary>Can you arrange delivery outside Palakkad?</summary><p>All-India transportation is available. Contact us to confirm delivery arrangements, access to your site, freight charges and timing for your order.</p></details><details><summary>Will fly ash bricks reduce my building cost?</summary><p>Consistent dimensions can help reduce mortar and finishing work. Actual project costs depend on the brick specification, local prices, transport and workmanship. Ask for a project-specific quote.</p></details></section>
<section className="contact section" id="contact"><div><p className="eyebrow">LET’S BUILD SOMETHING THAT LASTS</p><h2>Your next build.<br/><em>Let’s talk bricks.</em></h2><a className="phone" href="tel:+918075307418">+91 80753 07418 ↗</a><a href="tel:+919447033684">Also reach us: +91 94470 33684</a></div><div className="visit"><h3>Come by the factory.</h3><p>NEO BRICKS · Plot No. 84<br/>SIDCO Industrial Estate<br/>Puthupariyaram, Olavakkode<br/>Palakkad, Kerala 678731</p><a className="textlink" href="https://www.google.com/maps/search/?api=1&query=NEO+BRICKS+SIDCO+Puthupariyaram+Palakkad" target="_blank" rel="noreferrer">Get directions ↗</a><a href="mailto:bonychammany@gmail.com">bonychammany@gmail.com</a></div></section><footer><span>NEO BRICKS</span><p>Quality in every brick.</p><a href="#home">Back to top ↑</a></footer></main>}
